/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Conversation: typeof import('./src/components/Conversation.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MessageActions: typeof import('./src/components/MessageActions.vue')['default']
    MsgContent: typeof import('./src/components/MsgContent.vue')['default']
    MsgEditor: typeof import('./src/components/MsgEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
    WelcomeCard: typeof import('./src/components/WelcomeCard.vue')['default']
  }
}
